In [1]:
import numpy as np 

In [4]:
my_list=[ i for i in range(10)]
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
my_array = np.array(mylist)
my_array ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [8]:
mymatrix = np.array([[0,1,5],[-2,1,4],[7,8,9]])
mymatrix

array([[ 0,  1,  5],
       [-2,  1,  4],
       [ 7,  8,  9]])

In [10]:
 mymatrix[:,0:1]

array([[ 0],
       [-2],
       [ 7]])

In [15]:
mymatrix[0:3,1:2] #use colon for all rows

array([[1],
       [1],
       [8]])

In [17]:
mymatrix[0:2,2:3]

array([[5],
       [4]])

In [18]:
mymatrix[:,:]

array([[ 0,  1,  5],
       [-2,  1,  4],
       [ 7,  8,  9]])

# ARANGE

In [19]:
myarange = np.arange(10)
myarange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
myrangestep = np.arange(0,10,2)
myrangestep

array([0, 2, 4, 6, 8])

# zeros and ones

generate arrays of zeros and ones, REQUIRES TUPLES TO PRINT

In [22]:
Z = np.zeros(4)
Z

array([0., 0., 0., 0.])

In [24]:
Z3 = np.zeros((3,3))
Z3
            

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
O1 = np.ones(5)
O1

array([1., 1., 1., 1., 1.])

In [28]:
O6 = np.ones((6,6)) 
O6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# Linspace

Return evenly spaced numbers over a specified interval

In [34]:
L = np.linspace(1,25,36)
L

array([ 1.        ,  1.68571429,  2.37142857,  3.05714286,  3.74285714,
        4.42857143,  5.11428571,  5.8       ,  6.48571429,  7.17142857,
        7.85714286,  8.54285714,  9.22857143,  9.91428571, 10.6       ,
       11.28571429, 11.97142857, 12.65714286, 13.34285714, 14.02857143,
       14.71428571, 15.4       , 16.08571429, 16.77142857, 17.45714286,
       18.14285714, 18.82857143, 19.51428571, 20.2       , 20.88571429,
       21.57142857, 22.25714286, 22.94285714, 23.62857143, 24.31428571,
       25.        ])

In [42]:
L = np.linspace(1,25,9)
L

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [43]:
L3 =L.reshape(3,3)
L3

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

# Eye 

Creates an identity matrix, DOES NOT REQUIRE TUPLE TO PRINT

In [44]:
I2 = np.eye(2)
I2

array([[1., 0.],
       [0., 1.]])

In [48]:
I4 = np.eye(4,4)
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
I43 = np.eye(4,3)
I43

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [52]:
I43[0:2,0:2]

array([[1., 0.],
       [0., 1.]])

# Random

Create an array of the given shape an populate it with random smaples from a uniform distribution over [0,1]

In [53]:
import random

In [55]:
arr = np.random.rand(3,4) 
arr

array([[0.43305273, 0.06435531, 0.36481259, 0.17548234],
       [0.75817444, 0.28847634, 0.83491561, 0.12797259],
       [0.25821155, 0.66386385, 0.0359643 , 0.81250459]])

In [56]:
from numpy.random import rand

In [58]:
arr_simple = rand(3,4)
arr_simple

array([[0.6081537 , 0.9551507 , 0.09907633, 0.75880119],
       [0.21560031, 0.17839046, 0.13945092, 0.49589669],
       [0.41949008, 0.97871328, 0.5470129 , 0.72619708]])

# randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

In [59]:
from numpy.random import randn

In [61]:
mat = randn(3,2)
mat

array([[-0.3076433 , -0.61224816],
       [-0.55842775, -1.77288205],
       [-1.22414241,  0.56535133]])

# max, min, argmax, argmin 

These are useful methods for finding max or min values.Or to find their index locations using argmin or argmax.

In [ ]:
#ranarr = np.random.ran